# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zmY-TPtfAy_pzIzoX-MoXsE9NOqZLrbc
"""

def Universitet_xonasi(belgi):
  if belgi == "106-xona":
    return "1-etaj chap tarafda"
  elif belgi == "223-xona":
    return "2-etaj chap tarafda"
  elif belgi == "208-xona":
    return "2-etaj o'ng tarafda"
  elif belgi == "316-xona":
    return "3-etaj chap tarafda"
  elif belgi == "115-xona":
    return "1-etaj o'ng tarafda"
  elif belgi == "315-xona":
    return "3-etaj o'ng tarafda"
belgi=input("Kerakli xonani kiriting")
natija=Universitet_xonasi(belgi)
print(natija)